
package stubs.cashier;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CashierWebService", targetNamespace = "http://webservices/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CashierWebService {


    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "test", targetNamespace = "http://webservices/", className = "stubs.cashier.Test")
    @ResponseWrapper(localName = "testResponse", targetNamespace = "http://webservices/", className = "stubs.cashier.TestResponse")
    public void test();

    /**
     * 
     * @param forfait
     * @param creditCard
     * @throws PaymentException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "paye", targetNamespace = "http://webservices/", className = "stubs.cashier.Paye")
    @ResponseWrapper(localName = "payeResponse", targetNamespace = "http://webservices/", className = "stubs.cashier.PayeResponse")
    public void paye(
        @WebParam(name = "forfait", targetNamespace = "")
        String forfait,
        @WebParam(name = "creditCard", targetNamespace = "")
        String creditCard)
        throws PaymentException_Exception
    ;

}
