
package stubs;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ICashierWebService", targetNamespace = "http://webservice.isola3000.bf.unice.fr/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ICashierWebService {


    /**
     * 
     * @param forfait
     * @param creditCardNumber
     * @return
     *     returns boolean
     * @throws PaymentException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "payCardAndReload", targetNamespace = "http://webservice.isola3000.bf.unice.fr/", className = "stubs.PayCardAndReload")
    @ResponseWrapper(localName = "payCardAndReloadResponse", targetNamespace = "http://webservice.isola3000.bf.unice.fr/", className = "stubs.PayCardAndReloadResponse")
    public boolean payCardAndReload(
        @WebParam(name = "credit_card_number", targetNamespace = "")
        String creditCardNumber,
        @WebParam(name = "forfait", targetNamespace = "")
        Item forfait)
        throws PaymentException_Exception
    ;

    /**
     * 
     * @param forfait
     * @param creditCardNumber
     * @param cardId
     * @return
     *     returns boolean
     * @throws PaymentException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "payReloadCard", targetNamespace = "http://webservice.isola3000.bf.unice.fr/", className = "stubs.PayReloadCard")
    @ResponseWrapper(localName = "payReloadCardResponse", targetNamespace = "http://webservice.isola3000.bf.unice.fr/", className = "stubs.PayReloadCardResponse")
    public boolean payReloadCard(
        @WebParam(name = "card_id", targetNamespace = "")
        String cardId,
        @WebParam(name = "credit_card_number", targetNamespace = "")
        String creditCardNumber,
        @WebParam(name = "forfait", targetNamespace = "")
        Item forfait)
        throws PaymentException_Exception
    ;

}
