
package stubs.accessController;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AccessControllerServiceService", targetNamespace = "http://localhost:8080/isa/bf/accessControl", wsdlLocation = "file:/C:/Users/patch/Documents/GitHub/bf/client/src/resources/AccessControllerWS.wsdl")
public class AccessControllerServiceService
    extends Service
{

    private final static URL ACCESSCONTROLLERSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException ACCESSCONTROLLERSERVICESERVICE_EXCEPTION;
    private final static QName ACCESSCONTROLLERSERVICESERVICE_QNAME = new QName("http://localhost:8080/isa/bf/accessControl", "AccessControllerServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/patch/Documents/GitHub/bf/client/src/resources/AccessControllerWS.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ACCESSCONTROLLERSERVICESERVICE_WSDL_LOCATION = url;
        ACCESSCONTROLLERSERVICESERVICE_EXCEPTION = e;
    }

    public AccessControllerServiceService() {
        super(__getWsdlLocation(), ACCESSCONTROLLERSERVICESERVICE_QNAME);
    }

    public AccessControllerServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ACCESSCONTROLLERSERVICESERVICE_QNAME, features);
    }

    public AccessControllerServiceService(URL wsdlLocation) {
        super(wsdlLocation, ACCESSCONTROLLERSERVICESERVICE_QNAME);
    }

    public AccessControllerServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ACCESSCONTROLLERSERVICESERVICE_QNAME, features);
    }

    public AccessControllerServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AccessControllerServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IAccessControllerService
     */
    @WebEndpoint(name = "AccessControllerServicePort")
    public IAccessControllerService getAccessControllerServicePort() {
        return super.getPort(new QName("http://localhost:8080/isa/bf/accessControl", "AccessControllerServicePort"), IAccessControllerService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IAccessControllerService
     */
    @WebEndpoint(name = "AccessControllerServicePort")
    public IAccessControllerService getAccessControllerServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://localhost:8080/isa/bf/accessControl", "AccessControllerServicePort"), IAccessControllerService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ACCESSCONTROLLERSERVICESERVICE_EXCEPTION!= null) {
            throw ACCESSCONTROLLERSERVICESERVICE_EXCEPTION;
        }
        return ACCESSCONTROLLERSERVICESERVICE_WSDL_LOCATION;
    }

}
