
package stubs.accessController;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IAccessControllerService", targetNamespace = "http://webservice.isola3000.bf.unice.fr/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IAccessControllerService {


    /**
     * 
     * @param gateId
     * @param cardId
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "allowAccess", targetNamespace = "http://webservice.isola3000.bf.unice.fr/", className = "stubs.accessController.AllowAccess")
    @ResponseWrapper(localName = "allowAccessResponse", targetNamespace = "http://webservice.isola3000.bf.unice.fr/", className = "stubs.accessController.AllowAccessResponse")
    public boolean allowAccess(
        @WebParam(name = "card_id", targetNamespace = "")
        int cardId,
        @WebParam(name = "gate_id", targetNamespace = "")
        int gateId);

}
