<wsdl:definitions xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://localhost:8080/isa/bf/accessControl" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:ns2="http://schemas.xmlsoap.org/soap/http" xmlns:ns1="http://webservice.isola3000.bf.unice.fr/" name="AccessControllerServiceService" targetNamespace="http://localhost:8080/isa/bf/accessControl">
    <wsdl:import location="http://localhost:8080/bf-isola/webservices/AccessControllerWS?wsdl=IAccessControllerService.wsdl" namespace="http://webservice.isola3000.bf.unice.fr/"></wsdl:import>
    <wsdl:binding name="AccessControllerServiceServiceSoapBinding" type="ns1:IAccessControllerService">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="allowAccess">
            <soap:operation soapAction="" style="document"/>
            <wsdl:input name="allowAccess">
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output name="allowAccessResponse">
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="AccessControllerServiceService">
        <wsdl:port binding="tns:AccessControllerServiceServiceSoapBinding" name="AccessControllerServicePort">
            <soap:address location="http://localhost:8080/bf-isola/webservices/AccessControllerWS"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>